const LANGUAGES = {
	en: {
		name: 'English',
		flag: '🇬🇧',
		// Login
		appTitle: 'Quick Notes',
		enterCredentials: 'Enter your credentials to continue',
		username: 'Username',
		enterUsername: 'Enter your username',
		accessCode: 'Access Code',
		enterAccessCode: 'Enter access code',
		continue: 'Continue',
		welcome: 'Welcome',
		enterPassword: 'Enter your password',
		password: 'Password',
		signIn: 'Sign In',
		back: 'Back',
		forgotPassword: 'Forgot password?',
		// Create Account
		createAccount: 'Create Your Account',
		welcomeNewUser: 'Welcome <strong>{user}</strong>! Create a password to secure your notes.',
		confirmPassword: 'Confirm Password',
		minChars: 'Min. 6 characters',
		repeatPassword: 'Repeat password',
		createAccountBtn: 'Create Account',
		cancel: 'Cancel',
		// Recovery Code
		recoveryCodeTitle: 'Recovery Code',
		accountCreated: 'Account Created!',
		saveRecoveryCode: "Save this recovery code. You'll need it if you forget your password.",
		codeOnlyOnce: 'This code will only be shown once!',
		savedMyCode: "I've saved my code",
		// Reset Password
		resetPassword: 'Reset Password',
		enterRecoveryCode: 'Enter your recovery code to reset your password.',
		recoveryCode: 'Recovery Code',
		charCode: '8-character code',
		newPassword: 'New Password',
		resetPasswordBtn: 'Reset Password',
		passwordResetSuccess: 'Password reset successfully!',
		// Change Password
		changePassword: 'Change Password',
		enterNewPassword: 'Enter your new password',
		currentPassword: 'Current Password',
		yourCurrentPassword: 'Your current password',
		confirmNewPassword: 'Confirm New Password',
		repeatNewPassword: 'Repeat new password',
		changePasswordBtn: 'Change Password',
		passwordChanged: 'Password changed!',
		// Errors
		pleaseEnterUsername: 'Please enter your username.',
		pleaseEnterAccessCode: 'Please enter the access code.',
		pleaseEnterPassword: 'Please enter your password.',
		pleaseEnterCurrentPassword: 'Please enter your current password.',
		currentPasswordIncorrect: 'Current password is incorrect.',
		passwordMustBeDifferent: 'New password must be different from current password.',
		passwordMinLength: 'New password must be at least 6 characters.',
		passwordsNoMatch: 'New passwords do not match.',
		passwordsDontMatch: 'Passwords do not match.',
		passwordTooShort: 'Password must be at least 6 characters.',
		recoveryCodeLength: 'Recovery code must be 8 characters.',
		fillTitleContent: 'Please fill in both title and content.',
		// Notes
		notes: 'Notes',
		new: 'New',
		logout: 'Logout',
		noNotesYet: 'No notes yet',
		createFirstNote: 'Create your first note to get started!',
		view: 'View',
		edit: 'Edit',
		delete: 'Delete',
		deleteNote: 'Delete this note?',
		noteDeleted: 'Note deleted!',
		noteSaved: 'Note saved!',
		// Note Form
		newNote: 'New Note',
		editNote: 'Edit Note',
		title: 'Title',
		enterNoteTitle: 'Enter note title...',
		content: 'Content',
		writeNoteHere: 'Write your note here...',
		saveNote: 'Save Note',
		updateNote: 'Update Note',
		// Misc
		error: 'Error',
		serverError: 'Server error. Please try again.',
		created: 'Created',
		// Local Storage Mode
		useOffline: 'Use Offline',
		offlineMode: 'Offline Mode',
		localStorageWarning: 'Your notes will be stored locally in this browser only. Data may be lost if you clear browser data or use a different device.',
		localStorageWarningTitle: 'Local Storage Warning',
		understand: 'I understand',
		switchToServer: 'Switch to Server',
		offlineBadge: 'Offline'
	},

	de: {
		name: 'Deutsch',
		flag: '🇩🇪',
		appTitle: 'Quick Notes',
		enterCredentials: 'Anmeldedaten eingeben',
		username: 'Benutzername',
		enterUsername: 'Benutzername eingeben',
		accessCode: 'Zugangscode',
		enterAccessCode: 'Zugangscode eingeben',
		continue: 'Weiter',
		welcome: 'Willkommen',
		enterPassword: 'Passwort eingeben',
		password: 'Passwort',
		signIn: 'Anmelden',
		back: 'Zurück',
		forgotPassword: 'Passwort vergessen?',
		createAccount: 'Konto erstellen',
		welcomeNewUser: 'Willkommen <strong>{user}</strong>! Erstelle ein Passwort für deine Notizen.',
		confirmPassword: 'Passwort bestätigen',
		minChars: 'Mind. 6 Zeichen',
		repeatPassword: 'Passwort wiederholen',
		createAccountBtn: 'Konto erstellen',
		cancel: 'Abbrechen',
		recoveryCodeTitle: 'Wiederherstellungscode',
		accountCreated: 'Konto erstellt!',
		saveRecoveryCode: 'Speichere diesen Code. Du brauchst ihn, falls du dein Passwort vergisst.',
		codeOnlyOnce: 'Dieser Code wird nur einmal angezeigt!',
		savedMyCode: 'Code gespeichert',
		resetPassword: 'Passwort zurücksetzen',
		enterRecoveryCode: 'Gib deinen Wiederherstellungscode ein.',
		recoveryCode: 'Wiederherstellungscode',
		charCode: '8-stelliger Code',
		newPassword: 'Neues Passwort',
		resetPasswordBtn: 'Passwort zurücksetzen',
		passwordResetSuccess: 'Passwort zurückgesetzt!',
		changePassword: 'Passwort ändern',
		enterNewPassword: 'Neues Passwort eingeben',
		currentPassword: 'Aktuelles Passwort',
		yourCurrentPassword: 'Dein aktuelles Passwort',
		confirmNewPassword: 'Neues Passwort bestätigen',
		repeatNewPassword: 'Neues Passwort wiederholen',
		changePasswordBtn: 'Passwort ändern',
		passwordChanged: 'Passwort geändert!',
		pleaseEnterUsername: 'Bitte Benutzername eingeben.',
		pleaseEnterAccessCode: 'Bitte Zugangscode eingeben.',
		pleaseEnterPassword: 'Bitte Passwort eingeben.',
		pleaseEnterCurrentPassword: 'Bitte aktuelles Passwort eingeben.',
		currentPasswordIncorrect: 'Aktuelles Passwort ist falsch.',
		passwordMustBeDifferent: 'Neues Passwort muss sich vom aktuellen unterscheiden.',
		passwordMinLength: 'Passwort muss mind. 6 Zeichen haben.',
		passwordsNoMatch: 'Passwörter stimmen nicht überein.',
		passwordsDontMatch: 'Passwörter stimmen nicht überein.',
		passwordTooShort: 'Passwort muss mind. 6 Zeichen haben.',
		recoveryCodeLength: 'Wiederherstellungscode muss 8 Zeichen haben.',
		fillTitleContent: 'Bitte Titel und Inhalt ausfüllen.',
		notes: 'Notizen',
		new: 'Neu',
		logout: 'Abmelden',
		noNotesYet: 'Noch keine Notizen',
		createFirstNote: 'Erstelle deine erste Notiz!',
		view: 'Anzeigen',
		edit: 'Bearbeiten',
		delete: 'Löschen',
		deleteNote: 'Notiz löschen?',
		noteDeleted: 'Notiz gelöscht!',
		noteSaved: 'Notiz gespeichert!',
		newNote: 'Neue Notiz',
		editNote: 'Notiz bearbeiten',
		title: 'Titel',
		enterNoteTitle: 'Titel eingeben...',
		content: 'Inhalt',
		writeNoteHere: 'Notiz hier schreiben...',
		saveNote: 'Speichern',
		updateNote: 'Aktualisieren',
		error: 'Fehler',
		serverError: 'Serverfehler. Bitte erneut versuchen.',
		created: 'Erstellt',
		useOffline: 'Offline nutzen',
		offlineMode: 'Offline-Modus',
		localStorageWarning: 'Deine Notizen werden nur lokal in diesem Browser gespeichert. Daten können verloren gehen, wenn du die Browserdaten löschst oder ein anderes Gerät verwendest.',
		localStorageWarningTitle: 'Lokale Speicherung',
		understand: 'Verstanden',
		switchToServer: 'Zum Server wechseln',
		offlineBadge: 'Offline'
	},

	it: {
		name: 'Italiano',
		flag: '🇮🇹',
		appTitle: 'Quick Notes',
		enterCredentials: 'Inserisci le tue credenziali',
		username: 'Nome utente',
		enterUsername: 'Inserisci nome utente',
		accessCode: 'Codice di accesso',
		enterAccessCode: 'Inserisci codice di accesso',
		continue: 'Continua',
		welcome: 'Benvenuto',
		enterPassword: 'Inserisci la password',
		password: 'Password',
		signIn: 'Accedi',
		back: 'Indietro',
		forgotPassword: 'Password dimenticata?',
		createAccount: 'Crea il tuo account',
		welcomeNewUser: 'Benvenuto <strong>{user}</strong>! Crea una password per le tue note.',
		confirmPassword: 'Conferma password',
		minChars: 'Min. 6 caratteri',
		repeatPassword: 'Ripeti password',
		createAccountBtn: 'Crea account',
		cancel: 'Annulla',
		recoveryCodeTitle: 'Codice di recupero',
		accountCreated: 'Account creato!',
		saveRecoveryCode: 'Salva questo codice. Ti servirà se dimentichi la password.',
		codeOnlyOnce: 'Questo codice verrà mostrato solo una volta!',
		savedMyCode: 'Ho salvato il codice',
		resetPassword: 'Reimposta password',
		enterRecoveryCode: 'Inserisci il tuo codice di recupero.',
		recoveryCode: 'Codice di recupero',
		charCode: 'Codice di 8 caratteri',
		newPassword: 'Nuova password',
		resetPasswordBtn: 'Reimposta password',
		passwordResetSuccess: 'Password reimpostata!',
		changePassword: 'Cambia password',
		enterNewPassword: 'Inserisci la nuova password',
		currentPassword: 'Password attuale',
		yourCurrentPassword: 'La tua password attuale',
		confirmNewPassword: 'Conferma nuova password',
		repeatNewPassword: 'Ripeti nuova password',
		changePasswordBtn: 'Cambia password',
		passwordChanged: 'Password cambiata!',
		pleaseEnterUsername: 'Inserisci il nome utente.',
		pleaseEnterAccessCode: 'Inserisci il codice di accesso.',
		pleaseEnterPassword: 'Inserisci la password.',
		pleaseEnterCurrentPassword: 'Inserisci la password attuale.',
		currentPasswordIncorrect: 'Password attuale errata.',
		passwordMustBeDifferent: 'La nuova password deve essere diversa.',
		passwordMinLength: 'La password deve avere almeno 6 caratteri.',
		passwordsNoMatch: 'Le password non corrispondono.',
		passwordsDontMatch: 'Le password non corrispondono.',
		passwordTooShort: 'La password deve avere almeno 6 caratteri.',
		recoveryCodeLength: 'Il codice deve avere 8 caratteri.',
		fillTitleContent: 'Compila titolo e contenuto.',
		notes: 'Note',
		new: 'Nuova',
		logout: 'Esci',
		noNotesYet: 'Nessuna nota',
		createFirstNote: 'Crea la tua prima nota!',
		view: 'Visualizza',
		edit: 'Modifica',
		delete: 'Elimina',
		deleteNote: 'Eliminare questa nota?',
		noteDeleted: 'Nota eliminata!',
		noteSaved: 'Nota salvata!',
		newNote: 'Nuova nota',
		editNote: 'Modifica nota',
		title: 'Titolo',
		enterNoteTitle: 'Inserisci titolo...',
		content: 'Contenuto',
		writeNoteHere: 'Scrivi qui la tua nota...',
		saveNote: 'Salva',
		updateNote: 'Aggiorna',
		error: 'Errore',
		serverError: 'Errore del server. Riprova.',
		created: 'Creato',
		useOffline: 'Usa offline',
		offlineMode: 'Modalità offline',
		localStorageWarning: 'Le tue note saranno salvate solo localmente in questo browser. I dati potrebbero andare persi se cancelli i dati del browser o usi un altro dispositivo.',
		localStorageWarningTitle: 'Avviso archiviazione locale',
		understand: 'Ho capito',
		switchToServer: 'Passa al server',
		offlineBadge: 'Offline'
	},

	fr: {
		name: 'Français',
		flag: '🇫🇷',
		appTitle: 'Quick Notes',
		enterCredentials: 'Entrez vos identifiants',
		username: "Nom d'utilisateur",
		enterUsername: "Entrez votre nom d'utilisateur",
		accessCode: "Code d'accès",
		enterAccessCode: "Entrez le code d'accès",
		continue: 'Continuer',
		welcome: 'Bienvenue',
		enterPassword: 'Entrez votre mot de passe',
		password: 'Mot de passe',
		signIn: 'Se connecter',
		back: 'Retour',
		forgotPassword: 'Mot de passe oublié?',
		createAccount: 'Créer votre compte',
		welcomeNewUser: 'Bienvenue <strong>{user}</strong>! Créez un mot de passe pour vos notes.',
		confirmPassword: 'Confirmer le mot de passe',
		minChars: 'Min. 6 caractères',
		repeatPassword: 'Répéter le mot de passe',
		createAccountBtn: 'Créer le compte',
		cancel: 'Annuler',
		recoveryCodeTitle: 'Code de récupération',
		accountCreated: 'Compte créé!',
		saveRecoveryCode: 'Sauvegardez ce code. Vous en aurez besoin si vous oubliez votre mot de passe.',
		codeOnlyOnce: 'Ce code ne sera affiché qu\'une seule fois!',
		savedMyCode: 'J\'ai sauvegardé mon code',
		resetPassword: 'Réinitialiser le mot de passe',
		enterRecoveryCode: 'Entrez votre code de récupération.',
		recoveryCode: 'Code de récupération',
		charCode: 'Code de 8 caractères',
		newPassword: 'Nouveau mot de passe',
		resetPasswordBtn: 'Réinitialiser',
		passwordResetSuccess: 'Mot de passe réinitialisé!',
		changePassword: 'Changer le mot de passe',
		enterNewPassword: 'Entrez votre nouveau mot de passe',
		currentPassword: 'Mot de passe actuel',
		yourCurrentPassword: 'Votre mot de passe actuel',
		confirmNewPassword: 'Confirmer le nouveau mot de passe',
		repeatNewPassword: 'Répéter le nouveau mot de passe',
		changePasswordBtn: 'Changer le mot de passe',
		passwordChanged: 'Mot de passe changé!',
		pleaseEnterUsername: "Veuillez entrer votre nom d'utilisateur.",
		pleaseEnterAccessCode: "Veuillez entrer le code d'accès.",
		pleaseEnterPassword: 'Veuillez entrer votre mot de passe.',
		pleaseEnterCurrentPassword: 'Veuillez entrer votre mot de passe actuel.',
		currentPasswordIncorrect: 'Mot de passe actuel incorrect.',
		passwordMustBeDifferent: 'Le nouveau mot de passe doit être différent.',
		passwordMinLength: 'Le mot de passe doit avoir au moins 6 caractères.',
		passwordsNoMatch: 'Les mots de passe ne correspondent pas.',
		passwordsDontMatch: 'Les mots de passe ne correspondent pas.',
		passwordTooShort: 'Le mot de passe doit avoir au moins 6 caractères.',
		recoveryCodeLength: 'Le code doit avoir 8 caractères.',
		fillTitleContent: 'Veuillez remplir le titre et le contenu.',
		notes: 'Notes',
		new: 'Nouvelle',
		logout: 'Déconnexion',
		noNotesYet: 'Aucune note',
		createFirstNote: 'Créez votre première note!',
		view: 'Voir',
		edit: 'Modifier',
		delete: 'Supprimer',
		deleteNote: 'Supprimer cette note?',
		noteDeleted: 'Note supprimée!',
		noteSaved: 'Note sauvegardée!',
		newNote: 'Nouvelle note',
		editNote: 'Modifier la note',
		title: 'Titre',
		enterNoteTitle: 'Entrez le titre...',
		content: 'Contenu',
		writeNoteHere: 'Écrivez votre note ici...',
		saveNote: 'Sauvegarder',
		updateNote: 'Mettre à jour',
		error: 'Erreur',
		serverError: 'Erreur serveur. Veuillez réessayer.',
		created: 'Créé',
		useOffline: 'Utiliser hors ligne',
		offlineMode: 'Mode hors ligne',
		localStorageWarning: 'Vos notes seront stockées localement dans ce navigateur uniquement. Les données peuvent être perdues si vous effacez les données du navigateur ou utilisez un autre appareil.',
		localStorageWarningTitle: 'Avertissement stockage local',
		understand: 'Je comprends',
		switchToServer: 'Passer au serveur',
		offlineBadge: 'Hors ligne'
	},

	pt: {
		name: 'Português',
		flag: '🇧🇷',
		appTitle: 'Quick Notes',
		enterCredentials: 'Digite suas credenciais',
		username: 'Nome de usuário',
		enterUsername: 'Digite seu nome de usuário',
		accessCode: 'Código de acesso',
		enterAccessCode: 'Digite o código de acesso',
		continue: 'Continuar',
		welcome: 'Bem-vindo',
		enterPassword: 'Digite sua senha',
		password: 'Senha',
		signIn: 'Entrar',
		back: 'Voltar',
		forgotPassword: 'Esqueceu a senha?',
		createAccount: 'Criar sua conta',
		welcomeNewUser: 'Bem-vindo <strong>{user}</strong>! Crie uma senha para suas notas.',
		confirmPassword: 'Confirmar senha',
		minChars: 'Mín. 6 caracteres',
		repeatPassword: 'Repetir senha',
		createAccountBtn: 'Criar conta',
		cancel: 'Cancelar',
		recoveryCodeTitle: 'Código de recuperação',
		accountCreated: 'Conta criada!',
		saveRecoveryCode: 'Salve este código. Você precisará dele se esquecer sua senha.',
		codeOnlyOnce: 'Este código será mostrado apenas uma vez!',
		savedMyCode: 'Salvei meu código',
		resetPassword: 'Redefinir senha',
		enterRecoveryCode: 'Digite seu código de recuperação.',
		recoveryCode: 'Código de recuperação',
		charCode: 'Código de 8 caracteres',
		newPassword: 'Nova senha',
		resetPasswordBtn: 'Redefinir senha',
		passwordResetSuccess: 'Senha redefinida!',
		changePassword: 'Alterar senha',
		enterNewPassword: 'Digite sua nova senha',
		currentPassword: 'Senha atual',
		yourCurrentPassword: 'Sua senha atual',
		confirmNewPassword: 'Confirmar nova senha',
		repeatNewPassword: 'Repetir nova senha',
		changePasswordBtn: 'Alterar senha',
		passwordChanged: 'Senha alterada!',
		pleaseEnterUsername: 'Por favor, digite seu nome de usuário.',
		pleaseEnterAccessCode: 'Por favor, digite o código de acesso.',
		pleaseEnterPassword: 'Por favor, digite sua senha.',
		pleaseEnterCurrentPassword: 'Por favor, digite sua senha atual.',
		currentPasswordIncorrect: 'Senha atual incorreta.',
		passwordMustBeDifferent: 'A nova senha deve ser diferente.',
		passwordMinLength: 'A senha deve ter pelo menos 6 caracteres.',
		passwordsNoMatch: 'As senhas não coincidem.',
		passwordsDontMatch: 'As senhas não coincidem.',
		passwordTooShort: 'A senha deve ter pelo menos 6 caracteres.',
		recoveryCodeLength: 'O código deve ter 8 caracteres.',
		fillTitleContent: 'Por favor, preencha título e conteúdo.',
		notes: 'Notas',
		new: 'Nova',
		logout: 'Sair',
		noNotesYet: 'Nenhuma nota ainda',
		createFirstNote: 'Crie sua primeira nota!',
		view: 'Ver',
		edit: 'Editar',
		delete: 'Excluir',
		deleteNote: 'Excluir esta nota?',
		noteDeleted: 'Nota excluída!',
		noteSaved: 'Nota salva!',
		newNote: 'Nova nota',
		editNote: 'Editar nota',
		title: 'Título',
		enterNoteTitle: 'Digite o título...',
		content: 'Conteúdo',
		writeNoteHere: 'Escreva sua nota aqui...',
		saveNote: 'Salvar',
		updateNote: 'Atualizar',
		error: 'Erro',
		serverError: 'Erro no servidor. Tente novamente.',
		created: 'Criado',
		useOffline: 'Usar offline',
		offlineMode: 'Modo offline',
		localStorageWarning: 'Suas notas serão armazenadas localmente apenas neste navegador. Os dados podem ser perdidos se você limpar os dados do navegador ou usar outro dispositivo.',
		localStorageWarningTitle: 'Aviso de armazenamento local',
		understand: 'Entendi',
		switchToServer: 'Mudar para servidor',
		offlineBadge: 'Offline'
	},

	ja: {
		name: '日本語',
		flag: '🇯🇵',
		appTitle: 'Quick Notes',
		enterCredentials: '認証情報を入力してください',
		username: 'ユーザー名',
		enterUsername: 'ユーザー名を入力',
		accessCode: 'アクセスコード',
		enterAccessCode: 'アクセスコードを入力',
		continue: '続ける',
		welcome: 'ようこそ',
		enterPassword: 'パスワードを入力',
		password: 'パスワード',
		signIn: 'ログイン',
		back: '戻る',
		forgotPassword: 'パスワードを忘れた？',
		createAccount: 'アカウントを作成',
		welcomeNewUser: 'ようこそ <strong>{user}</strong>！メモを保護するパスワードを作成してください。',
		confirmPassword: 'パスワードを確認',
		minChars: '6文字以上',
		repeatPassword: 'パスワードを再入力',
		createAccountBtn: 'アカウント作成',
		cancel: 'キャンセル',
		recoveryCodeTitle: 'リカバリーコード',
		accountCreated: 'アカウント作成完了！',
		saveRecoveryCode: 'このコードを保存してください。パスワードを忘れた場合に必要です。',
		codeOnlyOnce: 'このコードは一度だけ表示されます！',
		savedMyCode: 'コードを保存しました',
		resetPassword: 'パスワードをリセット',
		enterRecoveryCode: 'リカバリーコードを入力してください。',
		recoveryCode: 'リカバリーコード',
		charCode: '8文字のコード',
		newPassword: '新しいパスワード',
		resetPasswordBtn: 'パスワードをリセット',
		passwordResetSuccess: 'パスワードがリセットされました！',
		changePassword: 'パスワードを変更',
		enterNewPassword: '新しいパスワードを入力',
		currentPassword: '現在のパスワード',
		yourCurrentPassword: '現在のパスワード',
		confirmNewPassword: '新しいパスワードを確認',
		repeatNewPassword: '新しいパスワードを再入力',
		changePasswordBtn: 'パスワードを変更',
		passwordChanged: 'パスワードが変更されました！',
		pleaseEnterUsername: 'ユーザー名を入力してください。',
		pleaseEnterAccessCode: 'アクセスコードを入力してください。',
		pleaseEnterPassword: 'パスワードを入力してください。',
		pleaseEnterCurrentPassword: '現在のパスワードを入力してください。',
		currentPasswordIncorrect: '現在のパスワードが正しくありません。',
		passwordMustBeDifferent: '新しいパスワードは現在のパスワードと異なる必要があります。',
		passwordMinLength: 'パスワードは6文字以上必要です。',
		passwordsNoMatch: 'パスワードが一致しません。',
		passwordsDontMatch: 'パスワードが一致しません。',
		passwordTooShort: 'パスワードは6文字以上必要です。',
		recoveryCodeLength: 'リカバリーコードは8文字です。',
		fillTitleContent: 'タイトルと内容を入力してください。',
		notes: 'メモ',
		new: '新規',
		logout: 'ログアウト',
		noNotesYet: 'メモがありません',
		createFirstNote: '最初のメモを作成しましょう！',
		view: '表示',
		edit: '編集',
		delete: '削除',
		deleteNote: 'このメモを削除しますか？',
		noteDeleted: 'メモが削除されました！',
		noteSaved: 'メモが保存されました！',
		newNote: '新しいメモ',
		editNote: 'メモを編集',
		title: 'タイトル',
		enterNoteTitle: 'タイトルを入力...',
		content: '内容',
		writeNoteHere: 'ここにメモを書いてください...',
		saveNote: '保存',
		updateNote: '更新',
		error: 'エラー',
		serverError: 'サーバーエラー。もう一度お試しください。',
		created: '作成日',
		useOffline: 'オフラインで使用',
		offlineMode: 'オフラインモード',
		localStorageWarning: 'メモはこのブラウザにのみローカル保存されます。ブラウザデータを消去したり、別のデバイスを使用すると、データが失われる可能性があります。',
		localStorageWarningTitle: 'ローカルストレージの警告',
		understand: '理解しました',
		switchToServer: 'サーバーに切り替え',
		offlineBadge: 'オフライン'
	},

	th: {
		name: 'ไทย',
		flag: '🇹🇭',
		appTitle: 'Quick Notes',
		enterCredentials: 'กรุณาใส่ข้อมูลประจำตัว',
		username: 'ชื่อผู้ใช้',
		enterUsername: 'ใส่ชื่อผู้ใช้',
		accessCode: 'รหัสเข้าใช้',
		enterAccessCode: 'ใส่รหัสเข้าใช้',
		continue: 'ดำเนินการต่อ',
		welcome: 'ยินดีต้อนรับ',
		enterPassword: 'ใส่รหัสผ่าน',
		password: 'รหัสผ่าน',
		signIn: 'เข้าสู่ระบบ',
		back: 'กลับ',
		forgotPassword: 'ลืมรหัสผ่าน?',
		createAccount: 'สร้างบัญชี',
		welcomeNewUser: 'ยินดีต้อนรับ <strong>{user}</strong>! สร้างรหัสผ่านเพื่อปกป้องบันทึกของคุณ',
		confirmPassword: 'ยืนยันรหัสผ่าน',
		minChars: 'อย่างน้อย 6 ตัวอักษร',
		repeatPassword: 'ใส่รหัสผ่านอีกครั้ง',
		createAccountBtn: 'สร้างบัญชี',
		cancel: 'ยกเลิก',
		recoveryCodeTitle: 'รหัสกู้คืน',
		accountCreated: 'สร้างบัญชีแล้ว!',
		saveRecoveryCode: 'บันทึกรหัสนี้ไว้ คุณจะต้องใช้ถ้าลืมรหัสผ่าน',
		codeOnlyOnce: 'รหัสนี้จะแสดงเพียงครั้งเดียว!',
		savedMyCode: 'บันทึกรหัสแล้ว',
		resetPassword: 'รีเซ็ตรหัสผ่าน',
		enterRecoveryCode: 'ใส่รหัสกู้คืนของคุณ',
		recoveryCode: 'รหัสกู้คืน',
		charCode: 'รหัส 8 ตัวอักษร',
		newPassword: 'รหัสผ่านใหม่',
		resetPasswordBtn: 'รีเซ็ตรหัสผ่าน',
		passwordResetSuccess: 'รีเซ็ตรหัสผ่านแล้ว!',
		changePassword: 'เปลี่ยนรหัสผ่าน',
		enterNewPassword: 'ใส่รหัสผ่านใหม่',
		currentPassword: 'รหัสผ่านปัจจุบัน',
		yourCurrentPassword: 'รหัสผ่านปัจจุบันของคุณ',
		confirmNewPassword: 'ยืนยันรหัสผ่านใหม่',
		repeatNewPassword: 'ใส่รหัสผ่านใหม่อีกครั้ง',
		changePasswordBtn: 'เปลี่ยนรหัสผ่าน',
		passwordChanged: 'เปลี่ยนรหัสผ่านแล้ว!',
		pleaseEnterUsername: 'กรุณาใส่ชื่อผู้ใช้',
		pleaseEnterAccessCode: 'กรุณาใส่รหัสเข้าใช้',
		pleaseEnterPassword: 'กรุณาใส่รหัสผ่าน',
		pleaseEnterCurrentPassword: 'กรุณาใส่รหัสผ่านปัจจุบัน',
		currentPasswordIncorrect: 'รหัสผ่านปัจจุบันไม่ถูกต้อง',
		passwordMustBeDifferent: 'รหัสผ่านใหม่ต้องแตกต่างจากรหัสผ่านปัจจุบัน',
		passwordMinLength: 'รหัสผ่านต้องมีอย่างน้อย 6 ตัวอักษร',
		passwordsNoMatch: 'รหัสผ่านไม่ตรงกัน',
		passwordsDontMatch: 'รหัสผ่านไม่ตรงกัน',
		passwordTooShort: 'รหัสผ่านต้องมีอย่างน้อย 6 ตัวอักษร',
		recoveryCodeLength: 'รหัสกู้คืนต้องมี 8 ตัวอักษร',
		fillTitleContent: 'กรุณาใส่หัวข้อและเนื้อหา',
		notes: 'บันทึก',
		new: 'ใหม่',
		logout: 'ออกจากระบบ',
		noNotesYet: 'ยังไม่มีบันทึก',
		createFirstNote: 'สร้างบันทึกแรกของคุณ!',
		view: 'ดู',
		edit: 'แก้ไข',
		delete: 'ลบ',
		deleteNote: 'ลบบันทึกนี้?',
		noteDeleted: 'ลบบันทึกแล้ว!',
		noteSaved: 'บันทึกแล้ว!',
		newNote: 'บันทึกใหม่',
		editNote: 'แก้ไขบันทึก',
		title: 'หัวข้อ',
		enterNoteTitle: 'ใส่หัวข้อ...',
		content: 'เนื้อหา',
		writeNoteHere: 'เขียนบันทึกที่นี่...',
		saveNote: 'บันทึก',
		updateNote: 'อัปเดต',
		error: 'ข้อผิดพลาด',
		serverError: 'ข้อผิดพลาดเซิร์ฟเวอร์ กรุณาลองใหม่',
		created: 'สร้างเมื่อ',
		useOffline: 'ใช้แบบออฟไลน์',
		offlineMode: 'โหมดออฟไลน์',
		localStorageWarning: 'บันทึกของคุณจะถูกเก็บไว้ในเบราว์เซอร์นี้เท่านั้น ข้อมูลอาจสูญหายหากคุณล้างข้อมูลเบราว์เซอร์หรือใช้อุปกรณ์อื่น',
		localStorageWarningTitle: 'คำเตือนการจัดเก็บในเครื่อง',
		understand: 'เข้าใจแล้ว',
		switchToServer: 'เปลี่ยนไปใช้เซิร์ฟเวอร์',
		offlineBadge: 'ออฟไลน์'
	},

	zh: {
		name: '中文',
		flag: '🇨🇳',
		appTitle: 'Quick Notes',
		enterCredentials: '请输入您的凭据',
		username: '用户名',
		enterUsername: '请输入用户名',
		accessCode: '访问码',
		enterAccessCode: '请输入访问码',
		continue: '继续',
		welcome: '欢迎',
		enterPassword: '请输入密码',
		password: '密码',
		signIn: '登录',
		back: '返回',
		forgotPassword: '忘记密码？',
		createAccount: '创建账户',
		welcomeNewUser: '欢迎 <strong>{user}</strong>！请为您的笔记创建密码。',
		confirmPassword: '确认密码',
		minChars: '至少6个字符',
		repeatPassword: '重复密码',
		createAccountBtn: '创建账户',
		cancel: '取消',
		recoveryCodeTitle: '恢复码',
		accountCreated: '账户已创建！',
		saveRecoveryCode: '请保存此恢复码。如果您忘记密码，将需要它。',
		codeOnlyOnce: '此代码只显示一次！',
		savedMyCode: '我已保存代码',
		resetPassword: '重置密码',
		enterRecoveryCode: '请输入您的恢复码。',
		recoveryCode: '恢复码',
		charCode: '8位代码',
		newPassword: '新密码',
		resetPasswordBtn: '重置密码',
		passwordResetSuccess: '密码已重置！',
		changePassword: '更改密码',
		enterNewPassword: '请输入新密码',
		currentPassword: '当前密码',
		yourCurrentPassword: '您的当前密码',
		confirmNewPassword: '确认新密码',
		repeatNewPassword: '重复新密码',
		changePasswordBtn: '更改密码',
		passwordChanged: '密码已更改！',
		pleaseEnterUsername: '请输入用户名。',
		pleaseEnterAccessCode: '请输入访问码。',
		pleaseEnterPassword: '请输入密码。',
		pleaseEnterCurrentPassword: '请输入当前密码。',
		currentPasswordIncorrect: '当前密码不正确。',
		passwordMustBeDifferent: '新密码必须与当前密码不同。',
		passwordMinLength: '密码至少需要6个字符。',
		passwordsNoMatch: '密码不匹配。',
		passwordsDontMatch: '密码不匹配。',
		passwordTooShort: '密码至少需要6个字符。',
		recoveryCodeLength: '恢复码必须是8个字符。',
		fillTitleContent: '请填写标题和内容。',
		notes: '笔记',
		new: '新建',
		logout: '退出',
		noNotesYet: '暂无笔记',
		createFirstNote: '创建您的第一个笔记！',
		view: '查看',
		edit: '编辑',
		delete: '删除',
		deleteNote: '删除此笔记？',
		noteDeleted: '笔记已删除！',
		noteSaved: '笔记已保存！',
		newNote: '新笔记',
		editNote: '编辑笔记',
		title: '标题',
		enterNoteTitle: '输入标题...',
		content: '内容',
		writeNoteHere: '在这里写笔记...',
		saveNote: '保存',
		updateNote: '更新',
		error: '错误',
		serverError: '服务器错误，请重试。',
		created: '创建于',
		useOffline: '离线使用',
		offlineMode: '离线模式',
		localStorageWarning: '您的笔记将仅存储在此浏览器本地。如果您清除浏览器数据或使用其他设备，数据可能会丢失。',
		localStorageWarningTitle: '本地存储警告',
		understand: '我明白了',
		switchToServer: '切换到服务器',
		offlineBadge: '离线'
	}
};

// Detect browser language
function detectBrowserLanguage() {
	const browserLang = navigator.language || navigator.userLanguage || 'en';
	const langCode = browserLang.split('-')[0].toLowerCase();
	// Check if we support this language
	if (LANGUAGES[langCode]) {
		return langCode;
	}
	return 'en';
}

// Current language (from localStorage or browser detection)
let currentLang = localStorage.getItem('lang') || detectBrowserLanguage();

// Get translation
function t(key, replacements = {}) {
	let text = LANGUAGES[currentLang]?.[key] || LANGUAGES['en'][key] || key;
	for (const [k, v] of Object.entries(replacements)) {
		text = text.replace(`{${k}}`, v);
	}
	return text;
}

// Set language
function setLanguage(lang) {
	if (LANGUAGES[lang]) {
		currentLang = lang;
		localStorage.setItem('lang', lang);
		return true;
	}
	return false;
}

// Get current language
function getLanguage() {
	return currentLang;
}

// Get all available languages
function getAvailableLanguages() {
	return Object.entries(LANGUAGES).map(([code, data]) => ({
		code,
		name: data.name,
		flag: data.flag
	}));
}
